'use strict';
module.exports = (sequelize, DataTypes) => {
  const Product = sequelize.define('Product', 
    {
      id: 
        {
          type: DataTypes.INTEGER(11),
          allowNull:false,
          autoIncrement: true,
          primaryKey: true
            },
      barcode: 
        {
          type: DataTypes.STRING(10),
          allowNull:false,
          defaultValue: '',
        },
      name: 
        {
          type: DataTypes.STRING(10),
          allowNull:false,
          defaultValue: ''
        },
      quantity:  
        {
          type: DataTypes.INT(20),
          allowNull:false,
          defaultValue: '0'
    },
    unit: {
        type: DataTypes.STRING(20),
        allowNull:false,
        defaultValue: ''
  }, 
    buy_price:
    {
      type: DataTypes.INT(10),
      allowNull:false,
    },
    price:
    {
      type: DataTypes.INT(10),
      allowNull:false,
    },
    photo:{
        type: DataTypes.STRING(10)
    },
    createdAt: {
      type: DataTypes.DATE,
      allowNull: false,
      _autoGenerated: true,
     // type: now() https://github.com/sequelize/sequelize-auto/issues/55
    },
    updatedAt: {
      type: DataTypes.DATE,
      allowNull: false,
      _autoGenerated: true,
      // type: now()
    },
    deletedAt: {
      type: DataTypes.DATE,
      allowNull: false,
      _autoGenerated: true,
      // type: now()
    }
  },
  

  );
  Product.associate = function(models) {
      models.product.hasMany(models.Invoice,{ onDelete: 'CASCADE' });
    };
  return User;
};
